---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine
  namespace: redmine
  labels:
    app: redmine-app
data:
  REDMINE_DB_POSTGRES: postgresql-service.postgresql
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_DATABASE: testdatabase
