---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql-app
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  PGDATA: /var/lib/postgresql/data/pgdata
