---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName:  csi-ceph-hdd-ms1
